name: em_bootcathon_env
channels:
  - defaults
dependencies:
  - python=3.10 # example
  - jupyter==1.0.0
  - pandas==2.2.1
  - numpy==1.26.4
  - scipy==1.13.0
  - scikit-learn==1.4.2
  - matplotlib==3.8.4
  - seaborn==0.12.2
  - ipykernel
